import { LegalShell } from "~/components/LegalShell";

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms & Conditions"
      updated="August 25, 2026"
      updatedIso="2026-08-25"
      slug="terms"
      description="The terms that govern your use of Radious — the personal AI radio station with hosts you hire, message and call live on air."
    >
        <p>
          These Terms &amp; Conditions (&ldquo;Terms&rdquo;) govern your access to and use of
          Radious, the personal AI radio service available at radious.ai and
          app.radious.ai (the &ldquo;Service&rdquo;). By creating an account or using the
          Service, you agree to these Terms.
        </p>

        <h2>1. The Service</h2>
        <p>
          Radious generates personalized radio shows that combine music, AI-generated
          host segments, news summaries, weather reports and calendar mentions. Hosts
          are artificial: their speech is generated by AI language and text-to-speech
          models. You can interact with them through on-air text messages and, on
          eligible plans, live voice calls.
        </p>

        <h2>2. Accounts</h2>
        <p>
          You need an account to use the Service. You must provide accurate
          information, keep your credentials secure, and be at least 16 years old (or
          the minimum age of digital consent in your country). You are responsible for
          activity under your account.
        </p>

        <h2>3. Beta access, plans and limits</h2>
        <ul>
          <li>
            The Service is currently in a free founding beta. Access is free, no
            payment method is required, and there is nothing to cancel. We may limit
            or withdraw beta access at any time.
          </li>
          <li>
            When paid plans begin, they will be billed monthly: Starter (3.99€, up to
            2 shows per day), Pro (7.99€, up to 20 shows, 1 studio call and 20 on-air
            messages per day) and Ultra (50€, up to 50 shows, 5 studio calls and 100
            on-air messages per day, plus founder community access and feature
            voting). Starter and Pro put up to 2 hosts on air and Ultra up to 3. The
            Banter and Learning host-talk types are part of Pro and Ultra; Facts and
            Philosophy are on every plan. We will tell you before any charge is ever
            made.
          </li>
          <li>
            Daily limits reset every 24 hours. To protect the Service we also apply
            technical usage ceilings that are independent of your plan. Limits and
            prices may change; we will notify you before changes affect a plan you
            already pay for.
          </li>
        </ul>

        <h2>4. Billing and cancellation</h2>
        <p>
          No charges are made during the beta. When paid plans begin, subscriptions
          will renew automatically each month until cancelled, you will be able to
          cancel anytime in the app, and your plan will remain active until the end of
          the paid period. Payments will be handled by a payment processor; we do not
          store your card details. Except where required by law, payments are
          non-refundable.
        </p>

        <h2>5. Acceptable use</h2>
        <ul>
          <li>Do not use the Service to generate or spread unlawful, hateful or harassing content, including through on-air messages or calls.</li>
          <li>Do not attempt to bypass usage limits, probe or disrupt the Service, or resell access to it.</li>
          <li>Do not use the Service to infringe anyone&rsquo;s intellectual property or privacy rights.</li>
        </ul>

        <h2>6. Music and third-party content</h2>
        <p>
          Free radio streams music from Audius and Jamendo under their respective
          licenses. Local file playback uses files you already own. You are
          responsible for having the right to play the content you bring to the
          Service. News segments summarize sources you configure; attribution stays
          with the original publishers.
        </p>

        <h2>7. AI-generated content</h2>
        <p>
          Host speech, news summaries, weather readings and call responses are
          generated by AI and can be inaccurate, incomplete or outdated. They are
          provided for entertainment and general information only and are not
          professional advice. Do not rely on them for medical, legal, financial or
          safety decisions.
        </p>

        <h2>8. Intellectual property</h2>
        <p>
          The Service, including its software, design and branding, belongs to Radious
          and its licensors. You keep the rights to the content you provide (feeds you
          select, messages you send, names you choose). You grant us the license
          needed to operate the Service, such as processing your messages so hosts can
          answer them on air.
        </p>

        <h2>9. Availability and changes</h2>
        <p>
          We aim for high availability but do not guarantee uninterrupted service.
          Current status is published at status.radious.ai. We may change or
          discontinue features; if we discontinue the Service entirely, we will give
          reasonable notice to paying subscribers.
        </p>

        <h2>10. Liability</h2>
        <p>
          To the maximum extent permitted by law, Radious is not liable for indirect
          or consequential damages, and our total liability for claims related to the
          Service is limited to the amount you paid us in the 12 months before the
          claim arose. Nothing in these Terms limits liability that cannot be limited
          by law.
        </p>

        <h2>11. Termination</h2>
        <p>
          You can delete your account in the app at any time, which removes your
          hosts, feeds, interests and history. We may suspend or terminate accounts
          that violate these Terms.
        </p>

        <h2>12. Governing law</h2>
        <p>
          These Terms are governed by the laws of the Republic of Estonia. Disputes
          are resolved by the courts of Estonia, without limiting mandatory consumer
          protections in your country of residence.
        </p>

        <h2>13. Contact</h2>
        <p>
          Questions about these Terms: <a href="mailto:support@radious.ai">support@radious.ai</a>.
        </p>
    </LegalShell>
  );
}
